#ifndef EXAMENESESTUDIANTE_H
#define EXAMENESESTUDIANTE_H

typedef enum {
    EXAMEN_MAT,
    EXAMEN_FISICA,
    EXAMEN_HISTORIA,
    EXAMEN_INGLES,
    EXAMEN_PROGRAMACION,
    EXAMEN_COMPLETO
} TipoExamen;

#endif // EXAMENESESTUDIANTE_H
