#ifndef SIMULACROEVENTOS_H
#define SIMULACROEVENTOS_H

typedef enum {
    EVACUACION,
    INCENDIO,
    SISMO,
    PRUEBA_DE_SONIDO,
    FUGA_DE_GAS,
    ALERTA_METEOROLOGICA,
    AMENAZA_BIOLOGICA,
    EJERCICIO_DE_SEGURIDAD,
    SIMULACRO_COMPLETADO
} EventoSimulacro;

#endif // SIMULACROEVENTOS_H
